runtime: nodejs20
instance_class: F1

handlers:
  - url: /(.*\.(gif|png|jpg|json|css|js|ico|svg))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|json|css|js|ico|svg)$

  - url: /.*
    secure: always
    script: auto

env_variables:
  NODE_ENV: 'production'