name: Process Newly Acquired Model Output Data

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ data-processing-event ]

# set concurrency group, cancels any other job already in progress from the
# same concurrency group
concurrency:
  group: update
  cancel-in-progress: true

jobs:
  transform-data:
    runs-on: ubuntu-latest
    steps:
      # access repo and set up python
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: install dependencies
        run: |
          pip install numpy
          pip install pandas
          pip install glob2

        # TODO make this dynamic, using a list of team names
      - name: Create subdirectory within data/processed
        shell: bash
        id: create-subdirectories-for-processed-data
        run: |
          mkdir -p data/processed
          mkdir -p data/processed/MOBS-GLEAM_FLUH
          mkdir -p data/processed/MIGHTE-Nsemble
          mkdir -p data/processed/NU_UCSD-GLEAM_AI_FLUH
          mkdir -p data/processed/CEPH-Rtrend_fluH

      # Run Remy's python script to transform the data and push to repo
      - name: execute transformation
        #TODO After setting up branch protection, refactor this so it creates a new branch and PR instead of pushing to main
        run: |
          python transform_data.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/processed/*
          git commit -m "transform data via github actions"
          git push