name: Scheduler & Dispatcher for Data Retrieval Workflows

run-name: scheduled time met, dispatching to other workflow...

on:
  workflow_dispatch:

  # Schedule a workflow to run at specific UTC times using POSIX cron syntax
  # Run the workflow every Wednesday
  # starting from 12:00PM until midnight, every 3 hours
  schedule:
    - cron: '30 6-21/3 * * 4'
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
#        - name: Checkout repository
#          uses: actions/checkout@v4
#          with:
#            submodules: 'true'

      - name: Dispatch data-retrieval workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: data-retrieval-event
          # might use payload in the future
          # client-payload: '{"ref":"main", "inputs": {"key": "value"}}'